[MCC-357251] Fix issue with matching substring references
braintree/open_api_parser pull request #13
Opened 2017-12-27 02:20 UTC by ssteeg-mdsol

A bug was introduced by https://github.com/braintree/open_api_parser/pull/10. If the pointer name was a substring of a previous pointer, the ref would be not be resolved.

For example, a definition called PersonInfoResponse would not resolve a ref to PersonInfo, because the `path.include?(escaped_pointer)` would return `true`. 

This fix adds a trailing slash so that the ref name is segmented and won't match the substring. Note that the path that is passed does not end with a "/", but the last part isn't involved in the matching. (e.g. The pointer `/definitions/personInfo` is checked inside the path `/paths//people/{id}/get/responses/200/schema/definitions/personInfoResponse/properties/info`)

@jfeltesse-mdsol @jcarres-mdsol @ykitamura-mdsol

2017-12-28 06:27 UTC, jcarres-mdsol commented
LGTM

2017-12-28 06:28 UTC, jcarres-mdsol commented
@drewolson ?

2018-01-02 14:50 UTC, drewolson requested changes
A few requested changes.

2018-01-02 14:50 UTC, drewolson commented on CHANGELOG.md
> +
Please add these changes to 1.3.0-dev.

2018-01-02 14:50 UTC, drewolson commented on lib/open_api_parser/pointer.rb
> +      path.include?("#{escaped_pointer}/")
Please remove these comments.

2018-01-02 14:50 UTC, drewolson commented on lib/open_api_parser/version.rb
> +  VERSION = "1.3.1".freeze
Don’t update the version here.

2018-01-04 07:58 UTC, ssteeg-mdsol commented
Thanks @drewolson, I've updated the PR for your comments

2018-01-04 13:26 UTC, drewolson approved these changes

2018-01-04 13:27 UTC, merged