Use `Addressable::URI.unencode` instead of obsoleted `URI.decode`
braintree/open_api_parser pull request #4
Opened 2017-05-30 04:43 UTC by jfeltesse-mdsol

with ruby 2.4.1 `URI.decode` (aka `unescape`) yields the following warnings:
```
escaped_pointer: warning: URI.unescape is obsolete
```

`Addressable::URI.unencode` looks like the closest replacement.
Bumped to 1.3 because of the new dependency on addressable.

2017-05-30 12:30 UTC, drewolson requested changes
Thanks for the PR! I've made a few small comments inline.

Also, can you share some information with me on why the move to `Addressable` is more correct than falling back to some other function or set of functions in the stdlib? I know that this is a complicated topic and I don't have a ton of information about other alternatives.

Thanks!

2017-05-30 12:30 UTC, drewolson commented on CHANGELOG.md
> +## 1.3.0
Would you mind just bumping the version to `1.2.1`? This feels like a bug fix to me.

2017-05-30 12:30 UTC, drewolson commented on lib/open_api_parser/pointer.rb
> +require "addressable/uri"
Can you please move this require to `lib/open_api_parser`?

2017-05-31 01:31 UTC, jfeltesse-mdsol commented
> Also, can you share some information with me on why the move to Addressable is more correct than falling back to some other function or set of functions in the stdlib? I know that this is a complicated topic and I don't have a ton of information about other alternatives.

I guess it depends what are the expected inputs and outputs.
The good ol' URI.unescape is obsoleted. There's an [alternative parser](http://ruby-doc.org/stdlib-2.4.1/libdoc/uri/rdoc/URI/RFC2396_Parser.html#method-i-unescape) based on RFC 2396, which is an almost 20 year old RFC [superseded by other RFCs](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Refinement_of_specifications).
Might be that the CGI escape/unescape are good enough in that case, I do not know this gem enough to be sure of this though (using `CGI.unescape` still makes the specs pass but are there specs covering the corner cases?).
There's a thorough [answer](https://stackoverflow.com/a/13059657) on SO about the slight differences.
The main reason I didn't dig too far and just used addressable is that it's pretty much the standard gem in the community to take care of URI stuff (see the [reverse dep](https://rubygems.org/gems/addressable/reverse_dependencies) graph on rubygems.org).
If just using CGI is enough in that case I agree that it's better to not introduce a new dependency.

2017-05-31 14:01 UTC, drewolson commented
@jfeltesse-mdsol Thanks, the reverse dep graph is very compelling. I like the idea of adding this dependency. Would you mind addressing the other concerns in the PR? If you do, I'll be happy to merge it.

Thanks!

2017-06-01 02:51 UTC, jfeltesse-mdsol commented
comments addressed

2017-06-01 18:34 UTC, drewolson approved these changes

2017-06-01 18:34 UTC, merged